### ISSUE TITLE
New PCB Config

### ISSUE THREAD

**Issue by speedcrafter442** [ChrGri/DIY-Sim-Racing-FFB-Pedal#15]
Stepper:
PUL : IO23 
DIR : IO22
TX : IO26
RX : IO27

ADC:
DRDY : IO19
DOUT : IO18
SCLK : IO15
DIN : IO13
CS : IO21

LOADCELL 1: A0/A1
LOADCELL 2: A2/A3
LOADCELL 3: A4/A5

Onboard LED : IO2

**Comment by ChrGri** [comment]
Pin definitions can be found here
https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal/blob/25eb67b6c5d8c9f64f3ea87a1a31fc1bc9e52b1e/Arduino/Esp32/Main/Main.h#L12

Board was tested successfully.
