### ISSUE TITLE
Esp 32 programing

### ISSUE THREAD

**Issue by B3N1321** [ChrGri/DIY-Sim-Racing-FFB-Pedal#30]
Hi, Could you possibly explain the programming of the esp32 via arduino IDE, unfortunately it gives me an error when I try

**Comment by ChrGri** [comment]
We moved to VS code, since it's much easier to use. Arduino IDE isn't supported anymore. You can find a tutorial here:
https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal/wiki/VScode-IDE-setup
