### ISSUE TITLE
ERRORS MAIN.INO

### ISSUE THREAD

**Issue by B3N1321** [ChrGri/DIY-Sim-Racing-FFB-Pedal#31]
There are many errors in the Main.ino code, variables, declarations, etc.  Does anyone have an idea what the problem might be?

**Comment by SupraDad** [comment]
Im also looking to program my pedals and having issues.

**Comment by ChrGri** [comment]
We moved to VS code, since it's much easier to use. Arduino IDE isn't supported anymore. You can find a tutorial here:
https://github.com/ChrGri/DIY-Sim-Racing-FFB-Pedal/wiki/VScode-IDE-setup
